### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by finnie2006** [hakanpy/discord.py#1]
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/container/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/levelsys.py", line 27, in on_message
    if message.channel.id in talk_channels:
TypeError: argument of type 'int' is not iterable
````

**Comment by finnie2006** [comment]
Fixed
